# Generated by Django 3.0.8 on 2020-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracks', '0003_auto_20200729_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='in_progress',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3),
        ),
    ]
