# Generated by Django 3.0.8 on 2020-08-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracks', '0005_ticket_ticket_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_progress',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
